// <copyright file="UnitTestExampleTest.GetFileContentUsingInterface.g.cs">Copyright ©  2013</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace UnitTesting.UnitTest
{
    public partial class UnitTestExampleTest
    {
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
[ExpectedException(typeof(InvalidOperationException))]
public void GetFileContentUsingInterfaceThrowsInvalidOperationException240()
{
    this.GetFileContentUsingInterface((string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
[ExpectedException(typeof(InvalidOperationException))]
public void GetFileContentUsingInterfaceThrowsInvalidOperationException431()
{
    this.GetFileContentUsingInterface("");
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void GetFileContentUsingInterface206()
{
    this.GetFileContentUsingInterface("\0");
}
    }
}
