// <copyright file="UnitTestExampleTest.Capitalize.g.cs">Copyright ©  2013</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace UnitTesting.UnitTest
{
    public partial class UnitTestExampleTest
    {
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void CapitalizeThrowsArgumentNullException431()
{
    string s;
    s = this.Capitalize((string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void Capitalize983()
{
    string s;
    s = this.Capitalize("");
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void Capitalize870()
{
    string s;
    s = this.Capitalize("\0");
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void Capitalize426()
{
    string s;
    s = this.Capitalize(":");
    Assert.AreEqual<string>("_", s);
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void Capitalize439()
{
    string s;
    s = this.Capitalize("a");
    Assert.AreEqual<string>("A", s);
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void Capitalize582()
{
    string s;
    s = this.Capitalize("a\0");
    Assert.AreEqual<string>("A", s);
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void Capitalize669()
{
    string s;
    s = this.Capitalize("aa");
    Assert.AreEqual<string>("Aa", s);
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void Capitalize393()
{
    string s;
    s = this.Capitalize(",\0");
    Assert.AreEqual<string>("_", s);
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void Capitalize727()
{
    string s;
    s = this.Capitalize("::");
    Assert.AreEqual<string>("__", s);
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void Capitalize411()
{
    string s;
    s = this.Capitalize("a.\u8061\0");
    Assert.AreEqual<string>("A_\u8061", s);
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void Capitalize538()
{
    string s;
    s = this.Capitalize("aaa");
    Assert.AreEqual<string>("Aaa", s);
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void Capitalize630()
{
    string s;
    s = this.Capitalize("a::a\0\0");
    Assert.AreEqual<string>("A__A", s);
}
    }
}
