// <copyright file="UnitTestExampleTest.CapitalizeReturnsOnlyLettersAndUnderscores.g.cs">Copyright ©  2013</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace UnitTesting.UnitTest
{
    public partial class UnitTestExampleTest
    {
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void CapitalizeReturnsOnlyLettersAndUnderscoresThrowsArgumentNullException348()
{
    this.CapitalizeReturnsOnlyLettersAndUnderscores((string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeReturnsOnlyLettersAndUnderscores922()
{
    this.CapitalizeReturnsOnlyLettersAndUnderscores("");
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeReturnsOnlyLettersAndUnderscores526()
{
    this.CapitalizeReturnsOnlyLettersAndUnderscores("\0");
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeReturnsOnlyLettersAndUnderscores364()
{
    this.CapitalizeReturnsOnlyLettersAndUnderscores(":");
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeReturnsOnlyLettersAndUnderscores152()
{
    this.CapitalizeReturnsOnlyLettersAndUnderscores("a");
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeReturnsOnlyLettersAndUnderscores467()
{
    this.CapitalizeReturnsOnlyLettersAndUnderscores("\u8061\0");
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeReturnsOnlyLettersAndUnderscores396()
{
    this.CapitalizeReturnsOnlyLettersAndUnderscores("aa");
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeReturnsOnlyLettersAndUnderscores747()
{
    this.CapitalizeReturnsOnlyLettersAndUnderscores(",\0");
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeReturnsOnlyLettersAndUnderscores217()
{
    this.CapitalizeReturnsOnlyLettersAndUnderscores("::");
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeReturnsOnlyLettersAndUnderscores868()
{
    this.CapitalizeReturnsOnlyLettersAndUnderscores("a.\u8061\0");
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeReturnsOnlyLettersAndUnderscores226()
{
    this.CapitalizeReturnsOnlyLettersAndUnderscores("aaa");
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeReturnsOnlyLettersAndUnderscores18()
{
    this.CapitalizeReturnsOnlyLettersAndUnderscores(".Ba:\0\0");
}
    }
}
