// <copyright file="UnitTestExampleTest.CapitalizeWillNotCapitalizeAgain.g.cs">Copyright ©  2013</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace UnitTesting.UnitTest
{
    public partial class UnitTestExampleTest
    {
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void CapitalizeWillNotCapitalizeAgainThrowsArgumentNullException94()
{
    this.CapitalizeWillNotCapitalizeAgain((string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeWillNotCapitalizeAgain922()
{
    this.CapitalizeWillNotCapitalizeAgain("");
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeWillNotCapitalizeAgain526()
{
    this.CapitalizeWillNotCapitalizeAgain("\0");
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeWillNotCapitalizeAgain364()
{
    this.CapitalizeWillNotCapitalizeAgain(":");
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeWillNotCapitalizeAgain152()
{
    this.CapitalizeWillNotCapitalizeAgain("a");
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeWillNotCapitalizeAgain396()
{
    this.CapitalizeWillNotCapitalizeAgain("aa");
}
[TestMethod]
[PexGeneratedBy(typeof(UnitTestExampleTest))]
public void CapitalizeWillNotCapitalizeAgain154()
{
    this.CapitalizeWillNotCapitalizeAgain(":aAdaaa::\u8061\0\0\0");
}
    }
}
